spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.18.0.3:8080/realms/time-tracker
server:
  port: 8082

keycloak:
  auth-server-url: http://localhost:8080/realms/time-tracker
  realm: time-tracker
  resource: front
